name = "FiniteElementSpace"
uuid = "438e068f-5bfb-4a1a-9f0e-9b2c8603b9a8"
version = "0.1.0"
authors = ["avieira <alexandre.vieira@lilo.org>"]

[deps]
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
GaussQuadrature = "0.5.8"
Gmsh = "0.3.1"
LinearAlgebra = "1.12.0"
Plots = "1.41.3"
SparseArrays = "1.11.0"
